version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # Alembic migrations (in backend/alembic)
    # alembic check, if it FAILS: alembic revision --autogenerate && alembic upgrade head
    # else: alembic upgrade head
    # + ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
    # + ["--reload"]
    # Extremely development only
    # IF ALEMBIC CHECK FAILS, RUN ALEMBIC UPGRADE HEAD
    command:  sh -c "alembic check || (alembic revision --autogenerate && alembic upgrade head) || alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8080 --reload"
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: on-failure
    env_file:
      - .env-dev
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: on-failure
volumes:
  postgres-data:
