require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
use_modular_headers!

#Convert all permission pods into static libraries
pre_install do |installer|
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}

  installer.pod_targets.each do |pod|
    if pod.name.eql?('RNPermissions') || pod.name.start_with?('Permission-')
      def pod.build_type;
        Pod::BuildType.static_library # >= CocoaPods 1.9
      end
    end
  end
end

target 'hear_you_out' do
  config = use_native_modules!

  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true
  use_react_native!(:path => config["reactNativePath"])

  # Build errors
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec', :modular_headers => false
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec', :modular_headers => false
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec', :modular_headers => false

  # Permission handlers (react-native-permissions)
  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'
  pod 'Permission-Notifications', :path => "../node_modules/react-native-permissions/ios/Notifications"
  pod 'Permission-Microphone', :path => "../node_modules/react-native-permissions/ios/Microphone"

  # Firebase
  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'


  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #use_flipper!({ 'Flipper' => '0.95.1', 'Flipper-Folly' => '2.6.7', 'Flipper-RSocket' => '1.4.3' })
  #post_install do |installer|
    #flipper_post_install(installer)
  #end
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'react-native-ffmpeg', :path => '../node_modules/react-native-ffmpeg'

  pod 'RNShare', :path => '../node_modules/react-native-share'

  pod 'RNFBAnalytics', :path => '../node_modules/@react-native-firebase/analytics'

  pod 'RNFBMessaging', :path => '../node_modules/@react-native-firebase/messaging'

end

