require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
use_modular_headers!

target 'hear_you_out' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # Build errors
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec', :modular_headers => false
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec', :modular_headers => false
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec', :modular_headers => false

  # Permission handlers (react-native-permissions)
  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'
  pod 'Permission-Microphone', :path => "../node_modules/react-native-permissions/ios/Microphone"


  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #use_flipper!({ 'Flipper' => '0.95.1', 'Flipper-Folly' => '2.6.7', 'Flipper-RSocket' => '1.4.3' })
  #post_install do |installer|
    #flipper_post_install(installer)
  #end
end

