"""empty message

Revision ID: 1c625be6d033
Revises: 5b9193a39e55
Create Date: 2023-12-18 13:43:46.380641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c625be6d033'
down_revision: Union[str, None] = '5b9193a39e55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Default to empty list
    op.add_column('questions', sa.Column('checklist', postgresql.ARRAY(sa.String()), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'checklist')
    # ### end Alembic commands ###
