"""empty message

Revision ID: 27595a2263b0
Revises: 14881ba58099
Create Date: 2024-01-31 12:56:47.042234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27595a2263b0'
down_revision: Union[str, None] = '14881ba58099'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topic_subscriptions')
    op.drop_column('users', 'firebase_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firebase_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('topic_subscriptions',
    sa.Column('topic', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('subscription_status', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='topic_subscriptions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='topic_subscriptions_pkey')
    )
    # ### end Alembic commands ###
