"""empty message

Revision ID: 70683dfdd8a0
Revises: 22503342879a
Create Date: 2024-01-15 15:05:19.060904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70683dfdd8a0'
down_revision: Union[str, None] = '22503342879a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('unique_views', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'unique_views')
    # ### end Alembic commands ###
