"""empty message

Revision ID: 84b35ca2bf4c
Revises: fd6b87fdfbcb
Create Date: 2023-11-11 13:24:18.749054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84b35ca2bf4c'
down_revision: Union[str, None] = 'fd6b87fdfbcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
