"""empty message

Revision ID: 91f37b4ee790
Revises: 70683dfdd8a0
Create Date: 2024-01-15 15:35:40.885076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91f37b4ee790'
down_revision: Union[str, None] = '70683dfdd8a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('views_count', sa.Integer(), nullable=False))
    op.add_column('answers', sa.Column('votes_count', sa.Integer(), nullable=False))
    op.add_column('answers', sa.Column('flags_count', sa.Integer(), nullable=False))
    op.drop_column('answers', 'views')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('views', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('answers', 'flags_count')
    op.drop_column('answers', 'votes_count')
    op.drop_column('answers', 'views_count')
    # ### end Alembic commands ###
